meta-freescale: Fix build error ERROR: waffle-1.7.2-r0 do_patch: Applying patch '0001-meson-Add-missing-wayland-dependency-on-EGL.patch'
Issue: LIN1023-1128

Update 'SRC_URI:imxgpu +=' to 'SRC_URI:append:imxgpu =' to avoid do_fetch error.
Update waffle_%.bbappend and 0001-meson-Add-missing-wayland-dependency-on-EGL.patch
to adapt to the current yocto version, which solves the following compilation error:

can't find file to patch at input line 19
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 87fc7761cff5931a58984c7f7e78f421a0660e0e Mon Sep 17 00:00:00 2001
|From: Tom Hochstein <tom.hochstein@nxp.com>
|Date: Wed, 22 Apr 2020 13:40:04 -0500
|Subject: [PATCH] meson: Add missing wayland dependency on EGL
|
|The build was not finding egl.pc due to this
|missing dependency.
|
|Upstream-Status: Pending
|
|Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
|
|---
| meson.build | 6 ++++--
| 1 file changed, 4 insertions(+), 2 deletions(-)
|
|--- a/meson.build
|+++ b/meson.build
--------------------------
No file to patch.  Skipping patch.
3 out of 3 hunks ignored
Patch 0001-meson-Add-missing-wayland-dependency-on-EGL.patch does not apply (enforce with -f)

(LOCAL REV: NOT UPSTREAM) - WRLinux specific.

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>